


countries_preselected = ['Afghanistan', 
                         'Albania', 
                         'Algeria', 
                         "Argentina", 
                         'Armenia', 
                         'Australia', 
                         'Austria',
                         'Azerbaijan', 
                         'Bahrain', 
                         'Bangladesh',
                         'Belarus',
                         'Belgium', 
                         'Bolivia', 
                         'Bulgaria',  
                         'China',
                         'Colombia',
                         'Congo (Kinshasa)',
                         'Costa Rica', 
                         'Cuba',
                         'Czechia',
                         'Denmark',
                         'Dominican Republic',
                         'Ecuador',
                         'Egypt',  
                         'Estonia', 
                         'Finland', 
                         'Georgia', 
                         'Germany', 
                         'Greece', 
                         'Hungary', 
                         'India', 
                         'Indonesia',
                         'Iran', 
                         'Iraq',
                         'Ireland', 
                         'Israel', 
                         'Italy', 
                         'Japan',
                         'Jordan', 
                         'Kenya', 
                         'Korea, South',
                         'Kosovo', 
                         'Kuwait' , 
                         'Lebanon',  
                         'Lithuania', 
                         'Malaysia', 
                         'Maldives', 
                         'Mali', 
                         'Mexico',
                         'Moldova', 
                         'Morocco', 
                         'Netherlands',
                         'Nigeria', 
                         'North Macedonia', 
                         'Norway',
                         'Pakistan', 
                         'Panama',  
                         'Paraguay',  
                         'Philippines',
                         'Poland', 
                         'Portugal', 
                         'Qatar', 
                         'Romania',
                         'Russia', 
                         'Saudi Arabia',
                         'Senegal',
                         'Serbia', 
                         'Singapore', 
                         'Slovakia', 
                         'South Africa',   
                         'Spain',   
                         'Switzerland',   
                         'Turkey', 
                         'US', 
                         'Ukraine',
                         'United Arab Emirates', 
                         'United Kingdom', 
                         'Uruguay', 
                         'Uzbekistan', 
                         "Venezuela"]


countries_JHU = ['Panama',
                 'Burkina Faso',
                 'Kazakhstan',
                 'Laos',
                 'Vietnam',
                 'Syria',
                 'Azerbaijan',
                 'Egypt',
                 'Botswana',
                 'Hungary',
                 'Afghanistan',
                 'Papua New Guinea',
                 'Paraguay',
                 'Cuba',
                 'El Salvador',
                 'Latvia',
                 'Cambodia',
                 'Moldova',
                 'Somalia',
                 'Dominican Republic',
                 'North Macedonia',
                 'Israel',
                 'Sri Lanka',
                 'Senegal',
                 'Singapore',
                 'Nigeria',
                 'Estonia',
                 'Turkey',
                 'Kiribati',
                 'Fiji',
                 'Montenegro',
                 'Chad',
                 'Sudan',
                 'Togo',
                 'Andorra',
                 'Seychelles',
                 "Cote d'Ivoire",
                 'Costa Rica',
                 'Russia',
                 'Samoa',
                 'Gabon',
                 'Kuwait',
                 'Nicaragua',
                 'Malawi',
                 'Czechia',
                 'Central African Republic',
                 'Eritrea',
                 'Brazil',
                 'Lebanon',
                 'Kenya',
                 'Liberia',
                 'Malaysia',
                 'Serbia',
                 'Albania',
                 'Norway',
                 'Uganda',
                 'Tanzania',
                 'Thailand',
                 'Suriname',
                 'Tonga',
                 'Bangladesh',
                 'Sweden',
                 'Slovenia',
                 'Mongolia',
                 'Venezuela',
                 'Ireland',
                 'Comoros',
                 'South Sudan',
                 'Portugal',
                 'Iceland',
                 'Haiti',
                 'Austria',
                 'Ukraine',
                 'Madagascar',
                 'Micronesia',
                 'Oman',
                 'Summer Olympics 2020',
                 'Timor-Leste',
                 'Antigua and Barbuda',
                 'Djibouti',
                 'South Africa',
                 'Saint Kitts and Nevis',
                 'Belarus',
                 'Denmark',
                 'Libya',
                 'Bahrain',
                 'Sierra Leone',
                 'Yemen',
                 'Trinidad and Tobago',
                 'Pakistan',
                 'Zambia',
                 'Iran',
                 'Congo (Brazzaville)',
                 'Greece',
                 'Lesotho',
                 'San Marino',
                 'US',
                 'Bahamas',
                 'China',
                 'Kyrgyzstan',
                 'Romania',
                 'Philippines',
                 'Armenia',
                 'Iraq',
                 'Zimbabwe',
                 'Bosnia and Herzegovina',
                 'Colombia',
                 'Grenada',
                 'Georgia',
                 'Tajikistan',
                 'Barbados',
                 "Congo (Kinshasa)",
                 'Indonesia',
                 'Chile',
                 'Cabo Verde',
                 'Holy See',
                 'Algeria',
                 'Kosovo',
                 'New Zealand',
                 'Poland',
                 'Malta',
                 'Taiwan*',
                 'West Bank and Gaza',
                 'Namibia',
                 'Equatorial Guinea',
                 'Ethiopia',
                 'Nepal',
                 'Jamaica',
                 'Morocco',
                 'France',
                 'Switzerland',
                 'Bhutan',
                 'Mexico',
                 'Uzbekistan',
                 'Rwanda',
                 'Guyana',
                 'India',
                 'Angola',
                 'Belgium',
                 'Benin',
                 'Netherlands',
                 'Mali',
                 'Palau',
                 'Korea, South',
                 'Argentina',
                 'Jordan',
                 'Marshall Islands',
                 'Belize',
                 'Solomon Islands',
                 'Japan',
                 'Sao Tome and Principe',
                 'United Arab Emirates',
                 'Burma',
                 'Liechtenstein',
                 'Dominica',
                 'United Kingdom',
                 'Maldives',
                 'Guinea-Bissau',
                 'Saudi Arabia',
                 'Spain',
                 'Ghana',
                 'Guatemala',
                 'Honduras',
                 'Germany',
                 'Mauritius',
                 'Niger',
                 'Canada',
                 'Finland',
                 'Gambia',
                 'Lithuania',
                 'Uruguay',
                 'Slovakia',
                 'Saint Vincent and the Grenadines',
                 'Croatia',
                 'Italy',
                 'Mauritania',
                 'Ecuador',
                 'Monaco',
                 'Qatar',
                 'Tunisia',
                 'Eswatini',
                 'Vanuatu',
                 'Australia',
                 'Peru',
                 'Bolivia',
                 'Cameroon',
                 'Saint Lucia',
                 'Guinea',
                 'Burundi',
                 'Cyprus',
                 'Mozambique',
                 'Brunei',
                 'Luxembourg',
                 'Bulgaria']

countries_US = ['Ohio',
                 'Michigan',
                 'Northern Mariana Islands',
                 'Idaho',
                 'Maine',
                 'Wisconsin',
                 'Illinois',
                 'Texas',
                 'Wyoming',
                 'American Samoa',
                 'Montana',
                 'New Jersey',
                 'Oregon',
                 'Massachusetts',
                 'North Carolina',
                 'Minnesota',
                 'Colorado',
                 'Arizona',
                 'Alaska',
                 'Mississippi',
                 'South Carolina',
                 'Kentucky',
                 'Virginia',
                 'Guam',
                 'Maryland',
                 'Puerto Rico',
                 'Tennessee',
                 'Alabama',
                 'Grand Princess',
                 'North Dakota',
                 'New Hampshire',
                 'Washington',
                 'Indiana',
                 'District of Columbia',
                 'New Mexico',
                 'West Virginia',
                 'Georgia',
                 'Kansas',
                 'Vermont',
                 'South Dakota',
                 'Nevada',
                 'Hawaii',
                 'Missouri',
                 'California',
                 'Virgin Islands',
                 'Rhode Island',
                 'Utah',
                 'Iowa',
                 'Delaware',
                 'Nebraska',
                 'Oklahoma',
                 'Louisiana',
                 'Arkansas',
                 'New York',
                 'Pennsylvania',
                 'Connecticut',
                 'Florida']
